# Generated by Django 6.0.2 on 2026-02-25 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CompanyInvestment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_empresa', models.CharField(max_length=255)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='company_logos/')),
                ('sector', models.CharField(blank=True, max_length=120)),
                ('pais', models.CharField(blank=True, max_length=120)),
                ('fecha_inversion', models.DateField(blank=True, null=True)),
                ('estado_inversion', models.CharField(choices=[('activa', 'Activa'), ('en_revision', 'En revisión'), ('desinvertida', 'Desinvertida'), ('pausada', 'Pausada')], default='activa', max_length=20)),
                ('porcentaje_participacion', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('valoracion_ultima_ronda', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('sitio_web', models.URLField(blank=True)),
                ('descripcion', models.TextField(blank=True)),
                ('datos_financieros', models.TextField(blank=True)),
                ('kpis_operativos', models.TextField(blank=True)),
                ('informes_rendimiento', models.TextField(blank=True)),
                ('ingresos_ultimo_ano', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('ebitda_ultimo_ano', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('beneficio_neto_ultimo_ano', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('crecimiento_operativo_ultimo_ano', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('numero_clientes_ultimo_ano', models.PositiveIntegerField(blank=True, null=True)),
                ('numero_informes_rendimiento', models.PositiveIntegerField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Inversión de empresa',
                'verbose_name_plural': 'Inversiones de empresas',
                'ordering': ['nombre_empresa'],
            },
        ),
    ]
