# Generated by Django 6.0.2 on 2026-02-25 19:20

from django.db import migrations, models
import django.db.models.deletion


def create_default_sectors(apps, schema_editor):
    Sector = apps.get_model("core", "Sector")
    defaults = [
        "Biotecnología",
        "Materiales Avanzados",
        "Energía",
        "Medtech",
        "Agrotech",
        "Otro",
    ]
    for name in defaults:
        Sector.objects.get_or_create(nombre=name)


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Sector",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("nombre", models.CharField(max_length=120, unique=True)),
            ],
            options={
                "verbose_name": "Sector",
                "verbose_name_plural": "Sectores",
                "ordering": ["nombre"],
            },
        ),
        migrations.AlterField(
            model_name="companyinvestment",
            name="sector",
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="inversiones", to="core.sector"),
        ),
        migrations.RunPython(create_default_sectors, migrations.RunPython.noop),
    ]
