# Generated by Django 6.0.2 on 2026-02-25 17:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_sector_model'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='companyinvestment',
            name='datos_financieros',
        ),
        migrations.RemoveField(
            model_name='companyinvestment',
            name='informes_rendimiento',
        ),
        migrations.RemoveField(
            model_name='companyinvestment',
            name='kpis_operativos',
        ),
    ]
