# Generated by Django 6.0.2 on 2026-02-25 19:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0003_remove_companyinvestment_datos_financieros_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="UserCompanyInvestment",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "company",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="user_links",
                        to="core.companyinvestment",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="company_links",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Empresa asociada a usuario",
                "verbose_name_plural": "Empresas asociadas a usuarios",
            },
        ),
        migrations.AddConstraint(
            model_name="usercompanyinvestment",
            constraint=models.UniqueConstraint(fields=("user", "company"), name="unique_user_company"),
        ),
    ]
