# Generated by Django 6.0.2 on 2026-02-25 20:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_usercompanyinvestment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='companyinvestment',
            name='nombre_empresa',
        ),
        migrations.RemoveField(
            model_name='companyinvestment',
            name='logo',
        ),
        migrations.RemoveField(
            model_name='companyinvestment',
            name='sector',
        ),
        migrations.RemoveField(
            model_name='companyinvestment',
            name='pais',
        ),
        migrations.RemoveField(
            model_name='companyinvestment',
            name='fecha_inversion',
        ),
        migrations.RemoveField(
            model_name='companyinvestment',
            name='estado_inversion',
        ),
        migrations.RemoveField(
            model_name='companyinvestment',
            name='porcentaje_participacion',
        ),
        migrations.RemoveField(
            model_name='companyinvestment',
            name='valoracion_ultima_ronda',
        ),
        migrations.RemoveField(
            model_name='companyinvestment',
            name='sitio_web',
        ),
        migrations.RemoveField(
            model_name='companyinvestment',
            name='descripcion',
        ),
        migrations.RemoveField(
            model_name='companyinvestment',
            name='ingresos_ultimo_ano',
        ),
        migrations.RemoveField(
            model_name='companyinvestment',
            name='ebitda_ultimo_ano',
        ),
        migrations.RemoveField(
            model_name='companyinvestment',
            name='beneficio_neto_ultimo_ano',
        ),
        migrations.RemoveField(
            model_name='companyinvestment',
            name='crecimiento_operativo_ultimo_ano',
        ),
        migrations.RemoveField(
            model_name='companyinvestment',
            name='numero_clientes_ultimo_ano',
        ),
        migrations.RemoveField(
            model_name='companyinvestment',
            name='numero_informes_rendimiento',
        ),
        migrations.AddField(
            model_name='companyinvestment',
            name='gd_sociedad',
            field=models.CharField(max_length=255, verbose_name='GD_SOCIEDAD'),
        ),
        migrations.AddField(
            model_name='companyinvestment',
            name='gd_internal_code',
            field=models.CharField(blank=True, max_length=120, verbose_name='GD_INTERNAL_CODE'),
        ),
        migrations.AddField(
            model_name='companyinvestment',
            name='gd_descripcion',
            field=models.TextField(blank=True, verbose_name='GD_DESCRIPCION'),
        ),
        migrations.AddField(
            model_name='companyinvestment',
            name='gd_logo',
            field=models.ImageField(blank=True, null=True, upload_to='company_logos/', verbose_name='GD_LOGO'),
        ),
        migrations.AddField(
            model_name='companyinvestment',
            name='gd_cif',
            field=models.CharField(blank=True, max_length=40, verbose_name='GD_CIF'),
        ),
        migrations.AddField(
            model_name='companyinvestment',
            name='gd_fecha_constitucion',
            field=models.DateField(blank=True, null=True, verbose_name='GD_FECHA_CONSTITUCION'),
        ),
        migrations.AddField(
            model_name='companyinvestment',
            name='gd_direccion',
            field=models.CharField(blank=True, max_length=255, verbose_name='GD_DIRECCION'),
        ),
        migrations.AddField(
            model_name='companyinvestment',
            name='gd_codigo_postal',
            field=models.CharField(blank=True, max_length=20, verbose_name='GD_CODIGO_POSTAL'),
        ),
        migrations.AddField(
            model_name='companyinvestment',
            name='gd_ciudad',
            field=models.CharField(blank=True, max_length=120, verbose_name='GD_CIUDAD'),
        ),
        migrations.AddField(
            model_name='companyinvestment',
            name='gd_provincia',
            field=models.CharField(blank=True, max_length=120, verbose_name='GD_PROVINCIA'),
        ),
        migrations.AddField(
            model_name='companyinvestment',
            name='gd_comunidad_autonoma',
            field=models.CharField(blank=True, max_length=120, verbose_name='GD_COMUNIDAD_AUTONOMA'),
        ),
        migrations.AddField(
            model_name='companyinvestment',
            name='gd_pais',
            field=models.CharField(blank=True, max_length=120, verbose_name='GD_PAIS'),
        ),
        migrations.AddField(
            model_name='companyinvestment',
            name='gd_website',
            field=models.URLField(blank=True, verbose_name='GD_Website'),
        ),
        migrations.AddField(
            model_name='companyinvestment',
            name='gd_linkedin',
            field=models.URLField(blank=True, verbose_name='GD_Linkedin'),
        ),
        migrations.AddField(
            model_name='companyinvestment',
            name='gd_ceo',
            field=models.CharField(blank=True, max_length=120, verbose_name='GD_CEO'),
        ),
        migrations.AddField(
            model_name='companyinvestment',
            name='gd_email_ceo',
            field=models.EmailField(blank=True, max_length=254, verbose_name='GD_Email_CEO'),
        ),
        migrations.AddField(
            model_name='companyinvestment',
            name='gd_phone_ceo',
            field=models.CharField(blank=True, max_length=40, verbose_name='GD_Phone_CEO'),
        ),
        migrations.AddField(
            model_name='companyinvestment',
            name='gd_persona_contacto_2',
            field=models.CharField(blank=True, max_length=120, verbose_name='GD_PERSONA_CONTACTO_2'),
        ),
        migrations.AddField(
            model_name='companyinvestment',
            name='gd_email_2',
            field=models.EmailField(blank=True, max_length=254, verbose_name='GD_EMAIL_2'),
        ),
        migrations.AddField(
            model_name='companyinvestment',
            name='gd_phone_2',
            field=models.CharField(blank=True, max_length=40, verbose_name='GD_PHONE_2'),
        ),
        migrations.AddField(
            model_name='companyinvestment',
            name='gd_persona_contacto_3',
            field=models.CharField(blank=True, max_length=120, verbose_name='GD_PERSONA_CONTACTO_3'),
        ),
        migrations.AddField(
            model_name='companyinvestment',
            name='gd_email_3',
            field=models.EmailField(blank=True, max_length=254, verbose_name='GD_EMAIL_3'),
        ),
        migrations.AddField(
            model_name='companyinvestment',
            name='gd_phone_3',
            field=models.CharField(blank=True, max_length=40, verbose_name='GD_PHONE_3'),
        ),
        migrations.AddField(
            model_name='companyinvestment',
            name='gd_opi',
            field=models.CharField(blank=True, max_length=120, verbose_name='GD_OPI'),
        ),
        migrations.AddField(
            model_name='companyinvestment',
            name='gd_organo_admon',
            field=models.CharField(blank=True, max_length=255, verbose_name='GD_ORGANO_ADMON'),
        ),
        migrations.AddField(
            model_name='companyinvestment',
            name='gd_fondo',
            field=models.CharField(blank=True, max_length=255, verbose_name='GD_FONDO'),
        ),
        migrations.AddField(
            model_name='companyinvestment',
            name='gd_fondo_miembro_equipo',
            field=models.CharField(blank=True, max_length=255, verbose_name='GD_FONDO_MIEMBRO_EQUIPO'),
        ),
        migrations.AddField(
            model_name='companyinvestment',
            name='cd_estadio',
            field=models.CharField(blank=True, max_length=120, verbose_name='CD_ESTADIO'),
        ),
        migrations.AddField(
            model_name='companyinvestment',
            name='cd_tech_sector',
            field=models.CharField(blank=True, max_length=120, verbose_name='CD_TECH_SECTOR'),
        ),
        migrations.AddField(
            model_name='companyinvestment',
            name='cd_tech_subsector',
            field=models.CharField(blank=True, max_length=120, verbose_name='CD_TECH_SUBSECTOR'),
        ),
        migrations.AddField(
            model_name='companyinvestment',
            name='cd_industrial_clasification',
            field=models.CharField(blank=True, max_length=120, verbose_name='CD_INDUSTRIAL_CLASIFICATION'),
        ),
        migrations.AddField(
            model_name='companyinvestment',
            name='cd_environmental_clasification',
            field=models.CharField(blank=True, max_length=120, verbose_name='CD_Environmental_Clasification'),
        ),
        migrations.AddField(
            model_name='companyinvestment',
            name='sd_valor_diferencial_tecnologico',
            field=models.TextField(blank=True, verbose_name='SD_VALOR_DIFERENCIAL_TECNOLOGICO'),
        ),
        migrations.AddField(
            model_name='companyinvestment',
            name='sd_valor_diferencial_mercado',
            field=models.TextField(blank=True, verbose_name='SD_VALOR_DIFERENCIAL_MERCADO'),
        ),
        migrations.AddField(
            model_name='companyinvestment',
            name='sd_propuesta_de_valor',
            field=models.TextField(blank=True, verbose_name='SD_PROPUESTA DE VALOR'),
        ),
        migrations.AddField(
            model_name='companyinvestment',
            name='sd_business_model',
            field=models.TextField(blank=True, verbose_name='SD_BUSINESS_MODEL'),
        ),
        migrations.AddField(
            model_name='companyinvestment',
            name='sd_clientes',
            field=models.TextField(blank=True, verbose_name='SD_CLIENTES'),
        ),
        migrations.AddField(
            model_name='companyinvestment',
            name='sd_competidores',
            field=models.TextField(blank=True, verbose_name='SD_COMPETIDORES'),
        ),
        migrations.AddField(
            model_name='companyinvestment',
            name='mkt_tam_descripcion',
            field=models.TextField(blank=True, verbose_name='MKT_TAM_Descripcion'),
        ),
        migrations.AddField(
            model_name='companyinvestment',
            name='mkt_tam_volume',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True, verbose_name='MKT_TAM_Volume'),
        ),
        migrations.AddField(
            model_name='companyinvestment',
            name='mkt_tam_value',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True, verbose_name='MKT_TAM_Value'),
        ),
        migrations.AddField(
            model_name='companyinvestment',
            name='mkt_tam_cagr',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, verbose_name='MKT_TAM_CAGR'),
        ),
        migrations.AddField(
            model_name='companyinvestment',
            name='mkt_sam_descripcion',
            field=models.TextField(blank=True, verbose_name='MKT_SAM_Descripcion'),
        ),
        migrations.AddField(
            model_name='companyinvestment',
            name='mkt_sam_volume',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True, verbose_name='MKT_SAM_Volume'),
        ),
        migrations.AddField(
            model_name='companyinvestment',
            name='mkt_sam_value',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True, verbose_name='MKT_SAM_Value'),
        ),
        migrations.AddField(
            model_name='companyinvestment',
            name='mkt_sam_cagr',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, verbose_name='MKT_SAM_CAGR'),
        ),
        migrations.AddField(
            model_name='companyinvestment',
            name='mkt_som_descripcion',
            field=models.TextField(blank=True, verbose_name='MKT_SOM_Descripcion'),
        ),
        migrations.AddField(
            model_name='companyinvestment',
            name='mkt_som_volume',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True, verbose_name='MKT_SOM_Volume'),
        ),
        migrations.AddField(
            model_name='companyinvestment',
            name='mkt_som_value',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True, verbose_name='MKT_SOM_Value'),
        ),
        migrations.AddField(
            model_name='companyinvestment',
            name='mkt_som_cagr',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, verbose_name='MKT_SOM_CAGR'),
        ),
        migrations.AddField(
            model_name='companyinvestment',
            name='exit_value',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True, verbose_name='EXIT_VALUE'),
        ),
        migrations.AddField(
            model_name='companyinvestment',
            name='exit_descripcion',
            field=models.TextField(blank=True, verbose_name='EXIT_DESCRIPCION'),
        ),
        migrations.AddField(
            model_name='companyinvestment',
            name='exit_empresas_comparables',
            field=models.TextField(blank=True, verbose_name='EXIT_EMPRESAS_COMPARABLES'),
        ),
        migrations.AlterModelOptions(
            name='companyinvestment',
            options={'ordering': ['gd_sociedad'], 'verbose_name': 'Empresa', 'verbose_name_plural': 'Empresas'},
        ),
    ]
