# Generated by Django 6.0.2 on 2026-03-02 18:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_tech_sector_model_and_fk'),
    ]

    operations = [
        migrations.CreateModel(
            name='VerticalClasification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255, unique=True)),
                ('orden', models.PositiveIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Vertical clasification',
                'verbose_name_plural': 'Vertical clasifications',
                'ordering': ['orden', 'nombre'],
            },
        ),
        migrations.AlterModelOptions(
            name='estadio',
            options={'ordering': ['orden', 'nombre'], 'verbose_name': 'Estadio', 'verbose_name_plural': 'Estadios'},
        ),
        migrations.AlterModelOptions(
            name='fondo',
            options={'ordering': ['orden', 'nombre'], 'verbose_name': 'Fondo', 'verbose_name_plural': 'Fondos'},
        ),
        migrations.AlterModelOptions(
            name='fondomiembroequipo',
            options={'ordering': ['orden', 'nombre'], 'verbose_name': 'Fondo miembro equipo', 'verbose_name_plural': 'Fondos miembros equipo'},
        ),
        migrations.AddField(
            model_name='companyinvestment',
            name='cd_vertical_clasification',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='companies', to='core.verticalclasification', verbose_name='CD_VERTICAL_CLASIFICATION'),
        ),
    ]
