# Generated by Django 6.0.2 on 2026-03-03 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_rename_cd_industrial_clasification_to_sector'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='companyinvestment',
            name='cd_environmental_clasification',
        ),
        migrations.AddField(
            model_name='companyinvestment',
            name='cd_industrial_subsector',
            field=models.CharField(blank=True, max_length=120, verbose_name='CD_INDUSTRIAL_SUBSECTOR'),
        ),
        migrations.AlterField(
            model_name='companyinvestment',
            name='cd_industrial_sector',
            field=models.CharField(blank=True, max_length=120, verbose_name='CD_INDUSTRIAL_SECTOR'),
        ),
    ]
