# Generated by Django 6.0.2 on 2026-03-17 15:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0022_initial_reference_data'),
    ]

    operations = [
        migrations.CreateModel(
            name='KPIEmpresa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('anio', models.PositiveIntegerField(verbose_name='Año')),
                ('trimestre', models.CharField(choices=[('Q1', 'Q1'), ('Q2', 'Q2'), ('Q3', 'Q3'), ('Q4', 'Q4')], max_length=2, verbose_name='Trimestre')),
                ('sociedad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='kpis', to='core.companyinvestment', verbose_name='Sociedad')),
            ],
            options={
                'verbose_name': 'KPI Empresa',
                'verbose_name_plural': 'KPIs Empresas',
                'ordering': ['sociedad', '-anio', 'trimestre'],
                'unique_together': {('sociedad', 'anio', 'trimestre')},
            },
        ),
    ]
