# Generated by Django 6.0.2 on 2026-03-17 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0023_kpiempresa'),
    ]

    operations = [
        migrations.AddField(
            model_name='kpiempresa',
            name='comercializacion',
            field=models.CharField(blank=True, choices=[('S', 'S'), ('N', 'N')], max_length=1, verbose_name='Comercialización'),
        ),
        migrations.AddField(
            model_name='kpiempresa',
            name='coste_energetico',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, verbose_name='Coste energético (% real vs estimado)'),
        ),
        migrations.AddField(
            model_name='kpiempresa',
            name='coste_materias_primas',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, verbose_name='Coste de materias primas (% real vs estimado)'),
        ),
        migrations.AddField(
            model_name='kpiempresa',
            name='estimated_breakeven_year',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Estimated Breakeven Year'),
        ),
        migrations.AddField(
            model_name='kpiempresa',
            name='estimated_time_to_market',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Estimated Time to Market'),
        ),
        migrations.AddField(
            model_name='kpiempresa',
            name='flagship_plant_terminada',
            field=models.CharField(blank=True, choices=[('S', 'S'), ('N', 'N')], max_length=1, verbose_name='Flagship Plant terminada'),
        ),
        migrations.AddField(
            model_name='kpiempresa',
            name='mrl',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5'), (6, '6'), (7, '7'), (8, '8'), (9, '9')], null=True, verbose_name='MRL'),
        ),
        migrations.AddField(
            model_name='kpiempresa',
            name='nombre',
            field=models.CharField(blank=True, max_length=255, verbose_name='Nombre'),
        ),
        migrations.AddField(
            model_name='kpiempresa',
            name='pilot_plant_terminada',
            field=models.CharField(blank=True, choices=[('S', 'S'), ('N', 'N')], max_length=1, verbose_name='Pilot Plant terminada'),
        ),
        migrations.AddField(
            model_name='kpiempresa',
            name='producto_flagship_validado',
            field=models.CharField(blank=True, choices=[('S', 'S'), ('N', 'N')], max_length=1, verbose_name='Producto de Flagship validado por cliente'),
        ),
        migrations.AddField(
            model_name='kpiempresa',
            name='producto_pilot_plant_validado',
            field=models.CharField(blank=True, choices=[('S', 'S'), ('N', 'N')], max_length=1, verbose_name='Producto de Pilot Plant / MVP validado por cliente'),
        ),
        migrations.AddField(
            model_name='kpiempresa',
            name='prueba_laboratorio_validada',
            field=models.CharField(blank=True, choices=[('S', 'S'), ('N', 'N')], max_length=1, verbose_name='Prueba de laboratorio validada'),
        ),
        migrations.AddField(
            model_name='kpiempresa',
            name='rendimiento_proceso',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, verbose_name='Rendimiento del proceso (% real vs estimado)'),
        ),
        migrations.AddField(
            model_name='kpiempresa',
            name='reproducibilidad_experimental',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, verbose_name='Reproducibilidad experimental (% de variabilidad entre ensayos)'),
        ),
        migrations.AddField(
            model_name='kpiempresa',
            name='trl',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5'), (6, '6'), (7, '7'), (8, '8'), (9, '9')], null=True, verbose_name='TRL'),
        ),
    ]
