# Generated by Django 6.0.2 on 2026-03-17 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0024_kpi_new_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='kpiempresa',
            name='acuerdos_colaboracion_clientes_firmados',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Acuerdos Colaboración Clientes firmados'),
        ),
        migrations.AddField(
            model_name='kpiempresa',
            name='acuerdos_distribucion_firmados',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Acuerdos Distribución firmados'),
        ),
        migrations.AddField(
            model_name='kpiempresa',
            name='loi_clientes_firmados',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='LOI Clientes firmados (vigentes)'),
        ),
        migrations.AddField(
            model_name='kpiempresa',
            name='ndas_clientes_firmados',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='NDAs Clientes firmados'),
        ),
        migrations.AddField(
            model_name='kpiempresa',
            name='nuevos_leads_clientes',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Nuevos Leads Clientes (contactados)'),
        ),
        migrations.AddField(
            model_name='kpiempresa',
            name='presupuestos_clientes_enviados',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Presupuestos Clientes enviados pendiente de firma (< 3 meses)'),
        ),
        migrations.AddField(
            model_name='kpiempresa',
            name='presupuestos_clientes_firmados',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Presupuestos Clientes firmados'),
        ),
        migrations.AddField(
            model_name='kpiempresa',
            name='qualified_clientes',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Qualified Clientes (interesados y estudiando los productos)'),
        ),
    ]
